#!/usr/bin/env python3
"""Turns a Vite `dist/` directory into C++ arrays for embedding.

Usage:
    generate_assets.py <dist_dir> <output_dir>

Emits embedded_assets.h / embedded_assets.cpp with:
    namespace embedded {
      struct Asset { const unsigned char* data; size_t size; };
      const std::unordered_map<std::string, Asset>& assets();
      const std::string& indexHtml();   // SPA fallback content
    }
Keys are the file paths relative to dist (e.g. "index.html", "assets/app.js").
"""

import os
import sys


def c_identifier(path: str) -> str:
    ident = "".join(c if c.isalnum() else "_" for c in path)
    if not ident or ident[0].isdigit():
        ident = "f_" + ident
    return ident


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    dist_dir, out_dir = sys.argv[1], sys.argv[2]
    os.makedirs(out_dir, exist_ok=True)

    files = []
    for root, _dirs, names in os.walk(dist_dir):
        for name in sorted(names):
            full = os.path.join(root, name)
            rel = os.path.relpath(full, dist_dir).replace(os.sep, "/")
            files.append((rel, full))
    files.sort()

    h_path = os.path.join(out_dir, "embedded_assets.h")
    c_path = os.path.join(out_dir, "embedded_assets.cpp")

    with open(h_path, "w", encoding="utf-8") as h:
        h.write("""#pragma once
#include <cstddef>
#include <string>
#include <unordered_map>

namespace embedded {
struct Asset {
  const unsigned char* data;
  size_t size;
};
const std::unordered_map<std::string, Asset>& assets();
const std::string& indexHtml();
}  // namespace embedded
""")

    with open(c_path, "w", encoding="utf-8") as c:
        c.write('// Generated by generate_assets.py — do not edit.\n')
        c.write('#include "embedded_assets.h"\n\n')

        for rel, full in files:
            with open(full, "rb") as f:
                data = f.read()
            ident = c_identifier(rel)
            c.write(f"static const unsigned char {ident}[] = {{\n")
            for i in range(0, len(data), 20):
                chunk = data[i : i + 20]
                c.write("  " + ", ".join(str(b) for b in chunk) + ",\n")
            c.write("};\n\n")

        c.write("namespace embedded {\n")
        c.write("const std::unordered_map<std::string, Asset>& assets() {\n")
        c.write("  static const std::unordered_map<std::string, Asset> m = {\n")
        for rel, _full in files:
            ident = c_identifier(rel)
            c.write('    {"%s", {%s, sizeof(%s)}},\n' % (rel, ident, ident))
        c.write("  };\n  return m;\n}\n")
        c.write("const std::string& indexHtml() {\n")
        c.write('  static const std::string s = std::string(\n')
        # index.html content, escaped for a C string literal
        idx = b""
        for r, full in files:
            if r == "index.html":
                with open(full, "rb") as f:
                    idx = f.read()
                break
        idx_str = idx.decode("utf-8", errors="replace")
        for line in idx_str.splitlines(keepends=True):
            esc = (
                line.replace("\\", "\\\\")
                .replace('"', '\\"')
                .replace("\n", "\\n")
                .replace("\r", "\\r")
            )
            c.write(f'    "{esc}"\n')
        c.write("  );\n  return s;\n}\n")
        c.write("}  // namespace embedded\n")

    print(f"embedded {len(files)} files -> {h_path}, {c_path}")


if __name__ == "__main__":
    main()
